<a href="https://colab.research.google.com/github/Sumanthbabu-Muthineni/CashWithdrawal/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#learning tensor flow fundamentals
More specifically i'm going to learn:
* introduction to tensors
* getting information from tensors
* manipulating tensors
* tensors & numpy
* using @tf.function( a way to speed up regular python functions)
* Using gpus with tensorflow or TPUS
* Exercises




# Introduction to tensors

In [3]:
#import tensor flow
import tensorflow as tf
print(tf.__version__)



2.18.0


In [5]:
#creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
#check no. of dimensions of a tensor (ndim stands for no. of dimensions)
scalar.ndim

0

In [9]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
#check dimension of vector
vector.ndim


1

In [12]:
#create a matrix (has more than one dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [13]:
matrix.ndim

2

In [15]:
#Create another matrix
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16) #specify the data type with dtype param. so here bydefault its taking int32 as dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [16]:
#whats the no. of dimensions of another_matrix?
another_matrix.ndim

2

In [18]:
#lets create a tensor
tensor=tf.constant([     [[1,2,3],[4,5,6]]  , [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]                  ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [19]:
tensor.ndim

3

what we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional array of numbers (where n can be any number ,for ex: a 0-dimensional tensor is a scalar ,a 1-dimensional tensor is a vector)


### Creating Tensors with `tf.Variable`

In [24]:
#Create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)